name: d_simple_parser
description: A simple and easy to use text parsing dart library, d_simple_parser comes with elegant parsers that you can use to build complex and more elegant parsers.
version: 1.0.5
homepage: https://github.com/magabe26/d_simple_parser
author: Edwin Magabe <edyma50@yahoo.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
